import React from 'react';

export default function BillPreview({ bill }) {
  if (!bill) return null;

  const totalAmount = bill.items.reduce((sum, item) => sum + item.sale * item.qty, 0);

  return (
    <div className="bill-preview-wrapper" id="printable-bill">
      <div className="bill-preview-header">
        <div>
          <div className="bill-preview-title">
            TAX INVOICE
            <small>Customer Copy</small>
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div className="bill-preview-tag">Invoice</div>
          <div style={{ fontSize: '11px', color: '#666', marginTop: '8px' }}>
            Generated by StockMaster
          </div>
        </div>
      </div>

      <div className="bill-preview-meta">
        <div className="bill-preview-box">
          <label>Bill Number</label>
          <span className="num-font">{bill.billNo}</span>
        </div>
        <div className="bill-preview-box">
          <label>Date</label>
          <span className="num-font">{bill.date}</span>
        </div>
        <div className="bill-preview-box" style={{ gridColumn: '1 / -1' }}>
          <label>Party / Customer</label>
          <span>{bill.party}</span>
          {bill.notes && (
            <div style={{ fontSize: '12px', color: '#555', marginTop: '6px', borderTop: '1px solid #eee', paddingTop: '4px' }}>
              <strong>Note:</strong> {bill.notes}
            </div>
          )}
        </div>
      </div>

      <table className="bill-preview-table">
        <thead>
          <tr>
            <th>Item Description</th>
            <th style={{ textAlign: 'center' }}>Qty</th>
            <th style={{ textAlign: 'right' }}>Rate (₹)</th>
            <th style={{ textAlign: 'right' }}>Amount (₹)</th>
          </tr>
        </thead>
        <tbody>
          {bill.items.map((item, index) => {
            const amount = item.sale * item.qty;
            return (
              <tr key={index}>
                <td>{item.name}</td>
                <td className="num-font" style={{ textAlign: 'center' }}>{item.qty}</td>
                <td className="num-font" style={{ textAlign: 'right' }}>₹{item.sale.toFixed(2)}</td>
                <td className="num-font" style={{ textAlign: 'right' }}>₹{amount.toFixed(2)}</td>
              </tr>
            );
          })}
        </tbody>
        <tfoot>
          <tr className="bill-preview-total-row">
            <td colSpan="3" style={{ textAlign: 'right' }}>Total Amount</td>
            <td className="num-font" style={{ textAlign: 'right' }}>₹{totalAmount.toFixed(2)}</td>
          </tr>
        </tfoot>
      </table>

      <div className="bill-preview-footer">
        Thank you for your business! • This is a computer-generated bill. • {bill.billNo}
      </div>
    </div>
  );
}
